### ISSUE TITLE
sky130 Makefile typo

### ISSUE THREAD

**Issue by standanley** [RTimothyEdwards/open_pdks#100]
I believe there is a small typo in the pull request merged on 1/26. I'm looking at line 160 in sky130/Makefile.in:
https://github.com/RTimothyEdwards/open_pdks/commit/66e53e5ba87a8f4133217512f73cabaac9adad8a#diff-110f5cdd52092b0ae64eac540e7fdc13a19e212e688d29e5420692503fd21b14R160

When adding the "libraries/" directory on the end of the --enable-sky130-pdk configuration value, it assigns the variable SKYWATER_PATH to itself using recursive assignment. This causes the error "Recursive variable 'SKYWATER_PATH' references itself".

One fix is to change the = to :=

But I think the intended behavior might be to append a copy of the path to itself with the /libraries added. In that case, I think we should change = to += on line 160, and = to := on line 158.

I'd appreciate it if someone more familiar with Makefiles and/or understanding of the intended behavior takes a look at this.

**Comment by RTimothyEdwards** [comment]
@standanley :  This was fixed already, but you need to get the repo from [(http://opencircuitdesign.com/open_pdks)].  The github repository is mirrored overnight unless I force a mirror manually.

**Comment by standanley** [comment]
Thank you!
