### ISSUE TITLE
I did not ask for osu library only sky but there is a file causing havoc

### ISSUE THREAD

**Issue by svenn71** [RTimothyEdwards/open_pdks#151]
Somehow the osu lib seems to be injected.
I only did ./configure --enable-sky130-pdk

sky130/sky130A/libs.tech/qflow/sky130Aosu.sh is empty and cause problem

```
FileNotFoundError: [Errno 2] No such file or directory: 'qflow/sky130_osu_sc_t18.sh'
make[2]: *** [Makefile:625: qflow-a] Error 1
make[2]: Leaving directory '/home/svennb/work/prg/git/open_pdks/sky130'
make[1]: *** [Makefile:562: all-a] Error 2
make[1]: Leaving directory '/home/svennb/work/prg/git/open_pdks/sky130'
make: *** [Makefile:103: tech_sky130] Error 2
```

**Comment by RTimothyEdwards** [comment]
Oops, I never pushed that change.  I just pushed it a few minutes ago, so please do a git pull and do the "configure" again.  Thanks for bringing it to my attention.

**Comment by svenn71** [comment]
the issue now fixed
