### ISSUE TITLE
LU factorization of the G Matrix failed

### ISSUE THREAD

**Issue by peijunh** [RTimothyEdwards/open_pdks#162]
Hello. I want to thank you for the update on common_pdn.tcl. After the update of @Manarabdelaty , I run my design with macro and get the error in the following figure. 

![37df10a78214610646fa36d7089aae8](https://user-images.githubusercontent.com/79550986/133871722-44938211-41da-4d88-9c1c-a9c3536c3bf7.png)

My macro includes a sensor and sky130_sram_4kbyte_1rw1r_32x1024_8. sensor use VDD and VSS as power pin and sram use vccd1 and vssd1 as its power pin. So I change the "set macro" in common_pdn.tcl as follows. 
>set macro {
>    orient {R0 R180 MX MY R90 R270 MXR90 MYR90}
>    power_pins "vccd1 VPWR VDD"
>    ground_pins "vssd1 VGND VSS"
>    blockages "li1 met1 met2 met3 met4"
>    straps {
>    }

Could you share suggestion and advice on this error? Thanks!

**Comment by getziadz** [comment]
I have encountered the same issue after the latest update.

**Comment by RTimothyEdwards** [comment]
Please contact @Manarabdelaty , who was last working on the PDN code.  I don't really have much to do with the openlane development;  I just get pull requests for updates and merge them.  The best place to get a fast response is the skywater-pdk slack workspace, #openlane channel.

**Comment by peijunh** [comment]
@getziadz I think we can try to set FP_PDN_IRDROP to 0 in config.tcl to avoid this.

**Comment by getziadz** [comment]
Yes. That worked for me too.

**Comment by getziadz** [comment]
Yes. That worked for me too.
