### ISSUE TITLE
The "all" build takes almost 2 hours due to capturing 

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#193]
From https://github.com/RTimothyEdwards/open_pdks/runs/4327353828?check_suite_focus=true 

The run `succeeded 2 hours ago in 1h 47m 35s` of which `1h 16m 53s` was used to create the tarball while only `29m 12s` was used in the building.

This is significantly longer than the other builds which average ~30 minutes;
![Screenshot from 2021-11-25 14-07-55](https://user-images.githubusercontent.com/21212/143503655-ce6b1140-670b-477e-aa21-5c4bef530141.png)

**Comment by RTimothyEdwards** [comment]
This is from the CI or something?  I don't have any idea what it's doing.

**Comment by mithro** [comment]
Yes, this is the GitHub Actions CI.

It is probably caused by using `--xz` compression on this line -> https://github.com/RTimothyEdwards/open_pdks/blob/master/.github/capture.sh#L43

**Comment by RTimothyEdwards** [comment]
I have no idea what that script is doing, or what it is intended to do.

**Comment by mithro** [comment]
The captures the output from the CI run so that GitHub Actions uploads it as described in https://github.com/RTimothyEdwards/open_pdks/pull/192

**Comment by RTimothyEdwards** [comment]
It is then probably more urgent to create a "debug level" option to open_pdks and restrict the output to have much less output by default.

**Comment by mithro** [comment]
Testing using gzip compression rather than xz @ https://github.com/mithro/open_pdks/commit/eb09f468da3e4f4514426267beb9f8a0f936c4e3 and https://github.com/mithro/open_pdks/actions/runs/1511101558

We will see if it makes much of a difference...

**Comment by mithro** [comment]
Fixed by #196.
