### ISSUE TITLE
Speed up execution by multithreading

### ISSUE THREAD

**Issue by hpretl** [RTimothyEdwards/open_pdks#216]
Since I often have to set up the PDK when using OpenLane etc., a shorter runtime would be nice. Maybe multi-threading some parts when working through different files would help?

**Comment by proppy** [comment]
I think `make -j` should be supported now thathttps://github.com/RTimothyEdwards/open_pdks/commit/7519dfb04400f224f140749cda44ee7de6f5e095 is merged.

**Comment by RTimothyEdwards** [comment]
I forgot that this was posted as an issue.  Yes, the open_pdks build is now fully multithreaded.  It will keep all processors fully loaded for at least 80% of the build time.

**Comment by hpretl** [comment]
Got it, thanks!
