### ISSUE TITLE
Add Open_PDKs, Magic Commits to .config/nodeinfo.json

### ISSUE THREAD

**Issue by donn** [RTimothyEdwards/open_pdks#226]
OpenLane does not store version numbers for either Open_PDKs or Magic. The changes required to resolve The-OpenROAD-Project/OpenLane#923 are thus going to be impossible.

```
    "build": {
	"magic": "8.3.209",
	"open_pdks": "1.0.255"
    }
```

I propose adding a similar field for commits:

```
    "build-commits": {
	"magic": "xxxxxx",
	"open_pdks": "xxxxxx"
    }
```

OpenLane will attempt to look for this field, and barring its existence, will fall back to the SOURCES file generated by the OpenLane `make pdk`.

**Comment by RTimothyEdwards** [comment]
I already did this.  See the last commit.  I have exactly what you propose except that "build-commits" is just "commit", and replaces the existing "commit" field which is only a single value representing the open_pdks commit.
