### ISSUE TITLE
`Min area of metal1 holes > 0.14um^2 (met1.7)` on designs hardened using the latest PDK

### ISSUE THREAD

**Issue by donn** [RTimothyEdwards/open_pdks#236]
See https://github.com/The-OpenROAD-Project/OpenLane/suites/5618555629/artifacts/182956314 for a full reproducible.

Minimal layout at: [layout.zip](https://github.com/RTimothyEdwards/open_pdks/files/8232524/layout.zip)

**Comment by RTimothyEdwards** [comment]
![min_metal_area_error](https://user-images.githubusercontent.com/12645599/157887677-79833a27-aaa8-4f3b-bb4f-d0574e3d19b8.png)

This is called "magic operating correctly".  Please take up the issue with OpenROAD.

The attached screenshot was taken at position (181.675um, 880.160um), (181.860um, 880.315um) in the layout, and clearly shows that the detail router has created a minimum metal hole violation.

**Comment by RTimothyEdwards** [comment]
This should be fixed now.  Please check and let me know, and I can close this issue.

**Comment by donn** [comment]
It is, thanks Tim.

**Comment by MohamedAliYounis** [comment]
How can I solve this problem, please? 
@RTimothyEdwards @donn

**Comment by donn** [comment]
@MohamedAliYounis If you're still experiencing it, please file an issue at the OpenLane repository.
