### ISSUE TITLE
Mismatch parameters not being replaced for all SPICE files

### ISSUE THREAD

**Issue by frbvianna** [RTimothyEdwards/open_pdks#247]
I have compiled the SkyWater PDK using open_pdks version **1.0.303** a while back. Looks like I had an issue during compilation related to [mismatch_params.py](../blob/1.0.303/sky130/custom/scripts/mismatch_params.py) script runtime, which did not break the build, but incurred in not having all necessary SPICE lib files replaced with the correct mismatch parameters for ngspice usage.

I see the following in sky130A_make.log, with a Traceback related to mismatch_params.py line 89 and what appears to be a short list of files with mismatch parameters:
![image](https://user-images.githubusercontent.com/59801837/161451439-0ed02ab3-4e7e-49e2-9f6a-c7ab97b879c3.png)

Although I haven't tried to compile it again in the latest version, my guess is that this issue could be related to 02a79f4c40f802d74f1d99d6d2ea6157c2d2f66f - I've recompiled the PDK with open_pdks **1.0.297** (one commit prior to that one) and seemingly all the parameters are correctly replaced.

**Comment by RTimothyEdwards** [comment]
I just pushed a fix for this (on opencircuitdesign.com).  I should have pushed it yesterday, but apparently I forgot.
