### ISSUE TITLE
[Minor issue] CLASS CORE SPACER missing for some spacers (Filler, decap, etc)

### ISSUE THREAD

**Issue by armleo** [RTimothyEdwards/open_pdks#270]
In some lefs the CLASS is wrong. They need to be core spacer. Otherwise they are used in density calculations by OpenROAD.

Locations:

https://github.com/RTimothyEdwards/open_pdks/blob/6003ab31478184bceedc76eb650d8812e0cd6f5b/sky130/custom/sky130_fd_sc_hd/lef/sky130_ef_sc_hd__decap_12.lef#L6

https://github.com/RTimothyEdwards/open_pdks/blob/6003ab31478184bceedc76eb650d8812e0cd6f5b/sky130/custom/sky130_fd_sc_hd/lef/sky130_ef_sc_hd__fill_12.lef#L6

And in the sky130_fd_sc_hd_decap_* cells.,

Needs to be:
```
CLASS CORE SPACER ;
```

![image](https://user-images.githubusercontent.com/7474152/184528332-017b9d2e-abf1-45f2-aa08-7ded9f3c3ffb.png)

**Comment by armleo** [comment]
I tried creating the patch files/pull requests, but because the test build required Magic VLSI + Open PDKs building, I am going to stop working on this issue.

Still issue needs fixing.

**Comment by RTimothyEdwards** [comment]
This is easy enough to do in open_pdks;  I just didn't notice your issue posted.  I saw your update post, so I have gone ahead and fixed all the issues and am testing the build and will push when confirmed.

**Comment by armleo** [comment]
@RTimothyEdwards Did you make the changes in the PDK cells too? (sky130_fd_sc_hd_decap_*)

**Comment by RTimothyEdwards** [comment]
Yes, I did.
