### ISSUE TITLE
How to update the PDK within open_pdks?

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [RTimothyEdwards/open_pdks#290]
Greetings,

Okay so perhaps this is a vague question with simple solutions, I know it is easy to update the pdk (sky130) if I have downloaded the pdk directly from the Github repository. But how would this work if my pdk is downloaded through the installation of open_pdks? Is it similar, just like go to `open_pdks/source` and do the submodule updates with git?

Thanks

**Comment by ChrisZonghaoLi** [comment]
Okay I just tested my hypothesis and yes it works with "go to open_pdks/source and do the submodule updates with git"

**Comment by RTimothyEdwards** [comment]
You can also do "make update" in open_pdks.
