### ISSUE TITLE
Repository is missing a LICENSE file

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#3]
https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by RTimothyEdwards** [comment]
@mithro :  We are going with Apache 2.0?

**Comment by mithro** [comment]
If you don't want to choose a license, chose Apache 2.0 - SGTM.

**Comment by RTimothyEdwards** [comment]
It's less a matter of choosing than a matter of making it compatible with the Google/SkyWater repository on which it depends.  Anyway, I added the license file, and it will show up in the github mirror in a few hours.
