### ISSUE TITLE
scripts/update.sh missing from repo

### ISSUE THREAD

**Issue by antonblanchard** [RTimothyEdwards/open_pdks#333]
The Makefiles refer to `scripts/update.sh` but I can't find it anywhere in the repo history.

**Comment by RTimothyEdwards** [comment]
Good question.  The intent of the script was to do a 'git pull' if the library was a git repository, or to remove it and re-do the download process if not.  I'm surprised that it just isn't anywhere to be found, but it's easy enough to write the script and add it.

**Comment by RTimothyEdwards** [comment]
Fixed in version 1.0.381.  The file was missing because there is a `.gitignore` file in the `scripts/` directory that is written to exclude all followed by a list of exceptions.  With `update.sh` never being added to that list, it never got committed to the repository.

**Comment by antonblanchard** [comment]
This is now upstream, so closing
