### ISSUE TITLE
Error regarding simulating inverter circuit in xschem with sky130

### ISSUE THREAD

**Issue by VanshikaTanwar** [RTimothyEdwards/open_pdks#350]
While simulating the inverter circuit with sky130 model then at that time it's showing this error that library file not included not found while I have given the correct path for the library of sky130. And I have checked that tt file is present at that library location .
As , I am trying to simulate the inverter circuit which I have made using MOSFET using sky130 models NMOS and PMOS  then ,due to this error it's not generating the waveform of inverter circuit . 

Ngspice version - version= ngspice-36

I have attached the generated netlist below :-
** sch_path:
*+ /home/vanshikatanwar/Desktop/vsdflow/work/tools/xschem_git/xschem_simulations/inverter.sch
**.subckt inverter
Vin Vin GND 0
.save i(vin)
Vdd VDD GND 1.8
.save i(vdd)
XM1 Vout Vin GND GND sky130_fd_pr__nfet_01v8 L=0.15 W=1 nf=1 ad='int((nf+1)/2) * W/nf * 0.29' as='int((nf+2)/2) * W/nf * 0.29'
+ pd='2*int((nf+1)/2) * (W/nf + 0.29)' ps='2*int((nf+2)/2) * (W/nf + 0.29)' nrd='0.29 / W' nrs='0.29 / W'
+ sa=0 sb=0 sd=0 mult=1 m=1
XM2 Vout Vin VDD VDD sky130_fd_pr__pfet_01v8 L=0.15 W=1 nf=1 ad='int((nf+1)/2) * W/nf * 0.29' as='int((nf+2)/2) * W/nf * 0.29'
+ pd='2*int((nf+1)/2) * (W/nf + 0.29)' ps='2*int((nf+2)/2) * (W/nf + 0.29)' nrd='0.29 / W' nrs='0.29 / W'
+ sa=0 sb=0 sd=0 mult=1 m=1
**** begin user architecture code

.control
.dc Vin 0 1.8 0.01
.save all
.endc

**** end user architecture code
**.ends
.GLOBAL VDD
.GLOBAL GND
.end

![IMG_20230212_140702](https://user-images.githubusercontent.com/90523478/218303278-bcca95e2-e283-4b0c-a128-b327bfce34d0.jpg)

![IMG20230212144716](https://user-images.githubusercontent.com/90523478/218303280-0509be77-2b1c-4d24-b924-8f2b31527611.jpg)

![IMG_20230212_145214](https://user-images.githubusercontent.com/90523478/218303284-8f8f76d1-f553-4c27-8893-ffbd7ef7eaca.jpg)

**Comment by RTimothyEdwards** [comment]
The specific error seems to be that it cannot find (path relative to the .lib file) `/usr/local/share/pdk/sky130A/libs.ref/sky130_fd_pr/spice/sky130_fd_pr__nfet_01v8__tt.corner.spice`.  Do you not have that file?

**Comment by VanshikaTanwar** [comment]
Yes, that file is present but ngspice file is not in the folder under libs.ref due to which the error was occuring ,so, I again installed the open_pdk then my error got solved . 
Thank you Rtimothy Edwards for your quick response .
