### ISSUE TITLE
Why are there two README files?

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#41]
There is a `README` and a `README.md` file the top level directory. I expected that `README` is older documentation that should be named something else?

**Comment by RTimothyEdwards** [comment]
Because I wrote a README file and then I mirrored it to github and github elected to add a README.md.

**Comment by RTimothyEdwards** [comment]
Can't think of a good alternative name.  It's not "older documentation" so much as just more in-depth documentation about the file structure that open_pdks generates and populates.

**Comment by mithro** [comment]
Sounds like developer documentation?

**Comment by mithro** [comment]
I just hit this issue again....

**Comment by mithro** [comment]
Fixed by #127

**Comment by RTimothyEdwards** [comment]
#127 has been pulled and merged, so closing this issue.
