### ISSUE TITLE
Build breaks when not building the sky130_osu_sc_t18 library

### ISSUE THREAD

**Issue by agorararmard** [RTimothyEdwards/open_pdks#45]
The build breaks when the sky130_osu_sc_t18 library is not there, because it tries to move the tlef file with the mv command without checking if the file exists or not, and so the build fails if it's not there (which will always be the case until the library is released).
```
mv `pwd`/sky130A/libs.ref/sky130_osu_sc_t18/techlef/sky130_osu_sc.tlef `pwd`/sky130A/libs.ref/sky130_osu_sc_t18/techlef/sky130_osu_sc_t18.tlef

mv: cannot stat `/home/travis/build/RTimothyEdwards/open_pdks/sky130/sky130A/libs.ref/sky130_osu_sc_t18/techlef/sky130_osu_sc.tlef': No such file or directory
```

The solution to this issue is in this PR #39, but it was closed without being merged :-)

**Comment by RTimothyEdwards** [comment]
I merged that, so I don't know why it appears either not to have happened, or reverted back to the way it was previously.  Anyway, I just did another commit to the master repo on opencircuitdesign.com with an attempt to do the renaming inside the foundry_install.py script.  Please check if it is correctly preserving the .tlef extension or not.

**Comment by agorararmard** [comment]
Roger that.

**Comment by agorararmard** [comment]
@RTimothyEdwards: an extra case was needed in the nested if handling the fileext. I added that in #46 .

**Comment by RTimothyEdwards** [comment]
Should be fixed now (will not appear in github until tomorrow morning, though).  I will leave the issue open until it is known good in the github repo.

**Comment by agorararmard** [comment]
Looks good to me!
