### ISSUE TITLE
Issue while running make command (Installing Open_Pdk)

### ISSUE THREAD

**Issue by neo-one-8** [RTimothyEdwards/open_pdks#466]
puts stdout "Done."
quit -noprompt

---------------------------------------------------------------------------
make[3]: *** [Makefile:1733: digital-lp-B] Error 1
make[3]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make[2]: *** [Makefile:1455: digital-lp-build-B] Error 2
make[2]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make[1]: *** [Makefile:1053: all-B] Error 2
make[1]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make: *** [Makefile:132: tech-sky130] Error 2

**Update :** When I run the make command with sudo (sudo make): 
I have the same errors but digital-lp-B is replaced with digital-lp-A and so on.

puts stdout "Done."
quit -noprompt

---------------------------------------------------------------------------

make[3]: *** [Makefile:1733: digital-lp-A] Error 1
make[3]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make[2]: *** [Makefile:1455: digital-lp-build-A] Error 2
make[2]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make[1]: *** [Makefile:1053: all-A] Error 2
make[1]: Leaving directory '/home/mrvenkat/open_pdks/sky130'
make: *** [Makefile:132: tech-sky130] Error 2

_MAGIC Version is : 8.3.500
Open_Pdk Verison : 1.0.500_

Update:
Im still facing this issue.
I looked at previous similar issues faced by others, which was dealt by either reinstalling the latest version of MAGIC or Open_Pdk. The versions of MAGIC and Open_Pdk that I have installed seems to be right, but unable to figure out whats wrong.
Any help would appreciated. Thank You.

**Comment by neo-one-8** [comment]
Hi, Im still facing this issue. 
I looked at previous similar issues faced by others, which was dealt by either reinstalling the latest version of MAGIC or Open_Pdk. The versions of MAGIC and Open_Pdk that I have installed seems to be right, but unable to figure out whats wrong.
Any help would appreciated. Thank You.

**Comment by matheus-VBLabs** [comment]
Hi Neo,

I encountered the same issue and discovered it was because I hadn't installed Magic. Once I installed Magic first and then the PDK, the error disappeared.

I noticed that you already have Magic installed, but this sequence worked for me: install Magic first, then the PDK.

I hope this helps!
