### ISSUE TITLE
Remove workaround for missing diodes

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#51]
With https://github.com/google/skywater-pdk/pull/204 being merged, I believe you need to remove the following script https://github.com/RTimothyEdwards/open_pdks/blob/master/sky130/custom/scripts/fix_missing_diodes_lef.py now?

**Comment by mithro** [comment]
@agorararmard

**Comment by RTimothyEdwards** [comment]
This has been updated in the master branch of the opencircuitdesign repo.

**Comment by RTimothyEdwards** [comment]
My script does in fact work for immediate mirrors on demand.  So the github repo has been updated, as has the opencircuitdesign website.
