### ISSUE TITLE
Give mithro Triage access to this repo

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#52]
Can haz pls?

**Comment by RTimothyEdwards** [comment]
If I give you access to the github version of the repository, you have to show me how to pull those changes into opencircuitdesign.com without breaking my local system.  The best way to get fast updates it to send a pull request, which I will expedite, especially if you send me a slack message at the same time.

**Comment by RTimothyEdwards** [comment]
I can do pull requests from my local computer and that works fine, so I assume I can do something similar to pull any changes made directly to the repository here.

**Comment by mithro** [comment]
Triage just gives me access to issues, not the code.

**Comment by RTimothyEdwards** [comment]
"Triage" is some official github thing, then?  How do I give you triage access?

**Comment by mithro** [comment]
`Settings > Manage Access` you can then add people and set their access level.

**Comment by mithro** [comment]
I can now change github issues :-).
