### ISSUE TITLE
Include git-describe --long information in all generated files

### ISSUE THREAD

**Issue by mithro** [RTimothyEdwards/open_pdks#56]
It would be good if when you generated files like the `sky130A.tech` file, you included the current git revision. The best way to do this is with `git-describe --long`.

**Comment by mithro** [comment]
You should also probably include `--dirty` and `--broken` too.

**Comment by RTimothyEdwards** [comment]
@mithro : The last thing I did along these lines was to add annotated tags. . . where in my process should I do this?  Before/after setting the tag?

**Comment by RTimothyEdwards** [comment]
@mithro :  Oh, I see what you mean.  I currently set "version" in the techfile to the datestamp (e.g., "20200508") but it could just as easily be set to the result of "git describe --long".

When you say "files like the sky130A.tech file", do you have other files in mind?

**Comment by mithro** [comment]
Any file which this repo creates.

**Comment by RTimothyEdwards** [comment]
@mithro :  Okay, done (for sky130A.tech).

**Comment by RTimothyEdwards** [comment]
Closing this issue, which was implemented a while ago (but more recently, took this a step further by keeping an information file in the installation with the commits of every repository used by open_pdks to compile the final installed PDK).
