### ISSUE TITLE
45 Degree Metal DRC Errors

### ISSUE THREAD

**Issue by yrrapt** [RTimothyEdwards/open_pdks#75]
Drawing 45 degree paths on metal 1 and 2 results in DRC errors but the DRC error states that 45 degree angles are allowed. Therefore I believe the DRC tool is not correctly interpreting the angles.
![image](https://user-images.githubusercontent.com/20978130/101239252-6af8cb80-36e6-11eb-9d00-682ab338c5ec.png)

[45degree_test.gds.zip](https://github.com/RTimothyEdwards/open_pdks/files/5646804/45degree_test.gds.zip)

Simple test case attached.

**Comment by RTimothyEdwards** [comment]
@yrrapt : Can you confirm that the angles are really 45 degrees?  A tiny difference in width vs. length will raise an error (both in magic and in calibre).  I have  had this problem myself.  How did you generate the angled wires?  It's possible that magic's "wire" command might have round-off issues;  if so, I'd need to fix them, but if you only have a few cases then you might be able to fix it by hand with "splitpaint" and "spliterase" commands.

**Comment by yrrapt** [comment]
On further inspection it was found that KLayout was not generating perfectly 45 degree paths.
Therefore, the problem is with KLayout and not open_pdks
